### ISSUE TITLE
Hi, thanks for your keras version of Adan, I use this code inst

### ISSUE THREAD

**Issue by wendongj** [cpuimage/keras-optimizer#1]
Hi, thanks for your keras version of Adan, I use this code instead adam optimizer. and update the rensorflow to 2.9.1, then it comes a wrong information:
    File "D:\code\Skip_DCCRN\Adan.py", line 117, in update_step
        p.assign(gradient)

    AttributeError: 'Tensor' object has no attribute 'assign'

**Comment by cpuimage** [comment]
@wendongj 你这里有可能是参数传错或者采用了tf.stop_gradient类似的做法，导致梯度传过来的不是变量而是标量。是错误使用，不是优化器实现的问题。
因为你 line 113是执行成功的，代表原始的p一开始确实是个变量，执行成功之后变成了Tensor，再次执行 line 117 由于属性改变，所以出错。
需要你自己自行排查一下自己的代码逻辑。
如果你想要忽略并强制处理的话， line 117 可以改写成这样。(但不确定是否可行，会不会引发其他问题）
`tf.compat.v1.assign(p, gradient, use_locking=True)`

**Comment by wendongj** [comment]
好的，多谢，我试一下
